/**
 * Notion Calendar Integration Utilities
 * 
 * Generates cron:// URLs for opening KINK IT calendar events in Notion Calendar.
 * 
 * Reference: https://www.notion.com/help/notion-calendar-integrations
 * 
 * The cron:// URL scheme allows opening specific calendar events in Notion Calendar
 * from external applications. This is a one-way integration (open events, not sync).
 */

export interface NotionCalendarUrlParams {
  /** Google account email the event belongs to (required) */
  accountEmail: string
  /** RFC5545 iCalendar UID (required) */
  iCalUID: string
  /** ISO 8601 start date/time (required) */
  startDate: string | Date
  /** ISO 8601 end date/time (required) */
  endDate: string | Date
  /** Event title (optional) */
  title?: string
  /** App referrer identifier (optional) */
  ref?: string
}

/**
 * Generates a cron:// URL for opening an event in Notion Calendar
 * 
 * @param params - Parameters for the Notion Calendar URL
 * @returns cron:// URL string
 * 
 * @example
 * ```typescript
 * const url = generateNotionCalendarUrl({
 *   accountEmail: '[email protected]',
 *   iCalUID: '123e4567-e89b-12d3-a456-426614174000@kink-it.app',
 *   startDate: '2025-02-05T20:30:00.000Z',
 *   endDate: '2025-02-05T21:00:00.000Z',
 *   title: 'Scene Planning',
 *   ref: 'kink-it'
 * })
 * ```
 */
export function generateNotionCalendarUrl(params: NotionCalendarUrlParams): string {
  const { accountEmail, iCalUID, startDate, endDate, title, ref = 'kink-it' } = params

  // Validate required parameters
  if (!accountEmail || !iCalUID || !startDate || !endDate) {
    throw new Error('Missing required parameters: accountEmail, iCalUID, startDate, and endDate are required')
  }

  // Format dates to ISO 8601 strings
  const formatDate = (date: string | Date): string => {
    if (typeof date === 'string') {
      return date
    }
    return date.toISOString()
  }

  const startDateStr = formatDate(startDate)
  const endDateStr = formatDate(endDate)

  // Build cron:// URL
  // Format from Notion docs: cron://[email protected]&[email protected]&startDate=2022-01-05T20:30:00.000Z&endDate=2022-01-05T21:00:00.000Z&title=Test&ref=com.example.test
  // Note: cron:// URLs use & as separators, not standard query parameters
  
  // URL encode values but keep & separators
  const encodedEmail = encodeURIComponent(accountEmail)
  const encodedICalUID = encodeURIComponent(iCalUID)
  const encodedStartDate = encodeURIComponent(startDateStr)
  const encodedEndDate = encodeURIComponent(endDateStr)
  const encodedTitle = title ? encodeURIComponent(title) : ''
  const encodedRef = encodeURIComponent(ref)

  // Construct URL with & separators
  let url = `cron://${encodedEmail}&${encodedICalUID}&startDate=${encodedStartDate}&endDate=${encodedEndDate}`
  
  if (encodedTitle) {
    url += `&title=${encodedTitle}`
  }
  
  url += `&ref=${encodedRef}`

  return url
}

/**
 * Opens a calendar event in Notion Calendar
 * 
 * @param url - cron:// URL generated by generateNotionCalendarUrl
 * @returns Promise that resolves when the URL is opened
 * 
 * @example
 * ```typescript
 * const url = generateNotionCalendarUrl({...})
 * await openInNotionCalendar(url)
 * ```
 */
export async function openInNotionCalendar(url: string): Promise<void> {
  // Check if we're in a browser environment
  if (typeof window === 'undefined') {
    throw new Error('openInNotionCalendar can only be called in a browser environment')
  }

  // For custom URL schemes like cron://, we need to navigate directly
  // Browsers will handle opening the app if installed, or show an error if not
  // We use a hidden iframe first to avoid navigating the main page
  return new Promise((resolve, reject) => {
    try {
      // Create a hidden iframe to attempt opening the URL
      // This prevents the main page from navigating if the app isn't installed
      const iframe = document.createElement('iframe')
      iframe.style.position = 'fixed'
      iframe.style.top = '-1000px'
      iframe.style.left = '-1000px'
      iframe.style.width = '1px'
      iframe.style.height = '1px'
      iframe.style.opacity = '0'
      iframe.style.pointerEvents = 'none'
      
      // Set a timeout - if the iframe doesn't trigger quickly, the app likely isn't installed
      const timeout = setTimeout(() => {
        // Clean up iframe
        if (document.body.contains(iframe)) {
          document.body.removeChild(iframe)
        }
        // Try direct navigation as fallback
        try {
          window.location.href = url
          // Give it a moment, then resolve (we can't really know if it worked)
          setTimeout(() => resolve(), 100)
        } catch (err) {
          reject(new Error('Failed to open Notion Calendar. Please make sure Notion Calendar is installed from https://www.notion.so/calendar'))
        }
      }, 250)

      // If iframe loads successfully, the URL scheme worked
      iframe.onload = () => {
        clearTimeout(timeout)
        setTimeout(() => {
          if (document.body.contains(iframe)) {
            document.body.removeChild(iframe)
          }
          resolve()
        }, 100)
      }

      // Add iframe to document and set src
      document.body.appendChild(iframe)
      iframe.src = url

      // Also set a shorter timeout to resolve if iframe doesn't error
      // (some browsers may not trigger onload for custom schemes)
      setTimeout(() => {
        if (document.body.contains(iframe)) {
          // If iframe is still there after 200ms, assume it worked
          clearTimeout(timeout)
          document.body.removeChild(iframe)
          resolve()
        }
      }, 200)
    } catch (error) {
      // If iframe approach fails, try direct navigation
      try {
        window.location.href = url
        setTimeout(() => resolve(), 100)
      } catch (navError) {
        reject(new Error('Failed to open Notion Calendar. Please make sure Notion Calendar is installed from https://www.notion.so/calendar'))
      }
    }
  })
}

/**
 * Checks if Notion Calendar is likely installed
 * 
 * Note: This is a best-effort check. We can't definitively detect
 * if Notion Calendar is installed without trying to open a URL.
 * 
 * @returns boolean indicating if Notion Calendar might be installed
 */
export function isNotionCalendarInstalled(): boolean {
  if (typeof window === 'undefined') {
    return false
  }

  // Check user agent for Notion Calendar indicators
  const userAgent = navigator.userAgent.toLowerCase()
  
  // Notion Calendar might set custom headers or user agent strings
  // This is a best-effort check
  return userAgent.includes('notion') || userAgent.includes('cron')
}

/**
 * Validates that a Google account email is in the correct format
 * 
 * @param email - Email address to validate
 * @returns boolean indicating if email is valid
 */
export function isValidGoogleEmail(email: string): boolean {
  const emailRegex = /^[^\s@]+@[^\s@]+\.[^\s@]+$/
  return emailRegex.test(email) && (email.endsWith('@gmail.com') || email.endsWith('@googlemail.com') || email.includes('@'))
}

